docs(categories): metod to  update category description
rees46/api-docs pull request #100
Opened 2024-08-27 13:06 UTC by gochicus

https://github.com/rees46/planning/issues/1528

2024-08-27 13:38 UTC, davidgegiya commented
@gochicus В апи-референсе импорта у нас в целом нет. Если делать, то делать его целиком, а не вставлять отдельный кусок.
Импорт у нас сейчас в документации описывается [здесь](https://rees46.ru/docs/ru/setup/products/api.html#загрузка-категории)

2024-09-02 06:11 UTC, gochicus commented
@davidgegiya посмотри пожалуйста, тут описание в рамках этой задачи. Остальной импорт отдельно перенесу.

2024-09-02 08:10 UTC, davidgegiya requested changes

2024-09-02 08:10 UTC, davidgegiya commented on source/includes/_import.md.erb
> +| external_id | true     | External ID                   |
Нет такого параметра. Метод поддерживает только `categories` и `webhook` (необязательный).
А для любых запросов, кроме `GET`, для авторизации всегда требуется помимо `shop_id`, также и `shop_secret`

2024-09-02 08:10 UTC, davidgegiya commented on source/includes/_import.md.erb
> +| categories  | true     | A category you want to update |
`categories` - это массив, а ты пишешь в единственном числе

2024-09-02 09:45 UTC, davidgegiya approved these changes

2024-09-02 10:32 UTC, TorinAsakura approved these changes

2024-09-02 10:32 UTC, merged