docs(recommendations): locations response parameter description change
rees46/api-docs pull request #101
Opened 2024-08-29 11:41 UTC by gochicus

https://github.com/rees46/planning/issues/1563

2024-08-29 12:25 UTC, Nelfimov requested changes

2024-08-29 12:25 UTC, Nelfimov commented on source/includes/_recommendations.md.erb
> +| locations       | array         | optionally             | A string with location IDs. IDs are separated by comma. If used, the API response will return products available in the listed locations.
тогда и `array` надо менять на `string`

2024-08-29 12:31 UTC, Nelfimov approved these changes

2024-08-30 07:27 UTC, TorinAsakura approved these changes

2024-08-30 07:27 UTC, merged