docs(stories): click listener description updated
rees46/api-docs pull request #106
Opened 2024-09-26 15:18 UTC by gochicus

https://github.com/rees46/planning/issues/1722

<details><summary>Пруф</summary>

<img width="1920" alt="stories clock proof" src="https://github.com/user-attachments/assets/e120a6cd-3bee-4a30-be83-308692f9eb91">

</details>

2024-09-26 15:19 UTC, DanielGreenEngineer approved these changes

2024-09-27 09:37 UTC, TorinAsakura requested changes

2024-09-27 09:37 UTC, TorinAsakura commented on source/includes/_stories.md.erb
> +  return false
тут тоже нужен отступ

2024-09-30 10:32 UTC, TorinAsakura approved these changes

2024-09-30 10:32 UTC, merged