docs(init): the warning and example for a dagger users
rees46/api-docs pull request #119
Opened 2024-10-21 14:54 UTC by gochicus

https://github.com/rees46/planning/issues/1859

<details><summary>Пруф</summary>

<img width="1920" alt="proof 23" src="https://github.com/user-attachments/assets/bfac15f3-9087-4ef3-b591-64037ecdbefe">

</details>

Этот ПР не закрывает задачу, инструкция будет в подразделе "Решение проблем" в секции "Подключение".  Здесь предупреждение, чтобы зависимости сходу не удаляли + пример.

2024-10-21 15:02 UTC, DanielGreenEngineer submitted a review, later dismissed

2024-10-22 11:20 UTC, TorinAsakura approved these changes

2024-10-22 11:20 UTC, TorinAsakura requested changes

2024-10-22 11:20 UTC, TorinAsakura commented on source/includes/_init.md.erb
> +An example is provided in this documentation. If you are having trouble switching to version 2.0 of the Android SDK or newer, refer to the troubleshooting section in our guides.
а текст по параграфам раскидать внутри контейнера не нужно?

2024-10-24 23:03 UTC, TorinAsakura requested changes

2024-10-24 23:03 UTC, TorinAsakura commented on source/includes/_init.md.erb
> +If your mobile application uses Dagger for dependency injection, make sure to keep the Dagger dependencies and the kapt plugin in your gradle files.
чо ты сделал? в p заверни блин

2024-10-25 10:57 UTC, TorinAsakura approved these changes

2024-10-25 10:57 UTC, merged