docs(init): popup response fieldes description
rees46/api-docs pull request #132
Opened 2024-11-26 15:14 UTC by gochicus

https://github.com/rees46/development/issues/2067

2025-01-23 07:43 UTC, davidgegiya requested changes
Можешь использовать эту ссылку, для проверки информации
https://api.rees46.ru/init?shop_id=357382bf66ac0ce2f1722677c59511&did=7Hvlb6ftsK

2025-01-23 07:43 UTC, davidgegiya commented on source/includes/_init.md.erb
> +### Popup response
Попапы являются частью общего ответа. Их не надо выделять как отдельный блок. Сделай по подобию параметре `search` выше (304 строка)

2025-01-23 07:43 UTC, davidgegiya commented on source/includes/_init.md.erb
> +| channels        | String (JSON) |
Это массив, а не строка

2025-01-23 07:43 UTC, davidgegiya commented on source/includes/_init.md.erb
> +| html            | String        |
Строка (HTML)

2025-01-23 07:43 UTC, davidgegiya commented on source/includes/_init.md.erb
> +| components      | String (HTML) |
Строка (JSON)

2025-02-07 07:33 UTC, davidgegiya commented
@gochicus

2025-02-10 15:17 UTC, davidgegiya submitted a review, later dismissed

2025-02-10 20:30 UTC, TorinAsakura requested changes

2025-02-10 20:30 UTC, TorinAsakura commented on source/includes/_init.md.erb
> +
зачем столько пустого пространства?

2025-02-11 10:36 UTC, TorinAsakura approved these changes

2025-02-11 10:36 UTC, merged