docs(orders): custom orders descr
rees46/api-docs pull request #15
Opened 2024-05-31 13:47 UTC by gochicus

2024-05-31 13:52 UTC, maksmart96 commented
@gochicus не подскажешь к какой задаче это относится? Не понимаю совсем что этот ПР описывает пока что

2024-05-31 16:04 UTC, xeewii approved these changes

2024-06-01 18:56 UTC, TorinAsakura requested changes

2024-06-01 18:56 UTC, TorinAsakura commented on source/includes/_orders.md.erb
> +```swift
а причём тут @xeewii если речь про свифт? Чот ничего не понимаю

2024-06-03 16:43 UTC, TorinAsakura approved these changes

2024-06-03 16:44 UTC, merged