docs(profile): change method description
rees46/api-docs pull request #23
Opened 2024-06-12 13:33 UTC by gochicus

Задача: https://github.com/rees46/planning/issues/723

Замена описания

2024-06-13 14:22 UTC, xeewii approved these changes

2024-06-14 11:42 UTC, TorinAsakura requested changes

2024-06-14 11:42 UTC, TorinAsakura commented on source/includes/_profile.md.erb
> +                override fun onSuccess(response: JSONObject?) {
отступы в порядок приведи
индент должен быть 2 и 4, а не как у тебя сейчас
через что ты себе так изуродовал отступы?

2024-06-17 12:12 UTC, TorinAsakura approved these changes

2024-06-17 12:12 UTC, merged