docs(search): fashion sizes example
rees46/api-docs pull request #41
Opened 2024-06-24 08:56 UTC by gochicus

К этой задаче: 
- https://github.com/rees46/planning/issues/228

2024-06-24 11:44 UTC, xeewii requested changes

2024-06-24 11:44 UTC, xeewii commented on source/includes/_search.md.erb
> +        params.put(SearchParams.Parameter.FILTERS, filters)
Здесь SearchParams.Parameter.FASHION_SIZES

2024-06-24 19:44 UTC, xeewii approved these changes

2024-06-25 08:52 UTC, TorinAsakura approved these changes

2024-06-25 08:52 UTC, merged