docs(products): cart delete method update description
rees46/api-docs pull request #47
Opened 2024-06-24 15:46 UTC by gochicus

к этой задаче:
- https://github.com/rees46/planning/issues/582

2024-06-24 16:24 UTC, noff requested changes

2024-06-24 16:24 UTC, noff commented on source/includes/_products.md.erb
> +At least of identifiers (marked by *) must present in request: email, phone, ect. It's used to identify user.
`ect` опечатка. Пожалуйста, внимательнее.

2024-06-25 06:36 UTC, noff approved these changes

2024-06-25 08:53 UTC, TorinAsakura approved these changes

2024-06-25 08:53 UTC, merged