docs(stories): change stories on request description
rees46/api-docs pull request #59
Opened 2024-07-01 15:23 UTC by gochicus

к этой задаче:
 - https://github.com/rees46/planning/issues/826

2024-07-01 15:24 UTC, xeewii approved these changes

2024-07-01 15:55 UTC, xeewii commented
Подними блок с инициализацией сторис выше в секцию "как работать со сторис"
![image](https://github.com/rees46/api-docs/assets/61105276/69ae56bb-5f8c-4e03-8904-b23b5c033140)

2024-07-02 06:58 UTC, gochicus commented
@xeewii посмотри, пожалуйста, так?

2024-07-02 07:07 UTC, xeewii submitted a review, later dismissed

2024-07-02 07:18 UTC, xeewii commented
И нужно вернуть документацию по джаве + добавить работу со сторисами из https://github.com/rees46/planning/issues/826#issuecomment-2200524336

2024-07-02 12:00 UTC, gochicus commented
@noff  можешь подсказать как работает дока, вот там есть в индексе таблица:
```
language_tabs:
  - shell: cURL
  - javascript: JavaScript
  - swift: iOS
  - kotlin: Android
  - jsx: React Native
```
В индексе обозначена структура страницы документации. Мне нужно вернуть джаву, и возникает такой вопрос: насколько эта структура жестко прописана? Например,  сделаю так:
```
language_tabs:
  - shell: cURL
  - javascript: JavaScript
  - swift: iOS
  - kotlin: Android
  - java: Android
  - jsx: React Native
  ```
Добавится ли новая вкладка слева или просто всё развалится?

2024-07-02 12:04 UTC, noff commented
@gochicus пошли в дискорд, посмотрим.

2024-07-02 15:06 UTC, Nelfimov approved these changes

2024-07-03 14:14 UTC, gochicus commented
@xeewii вернул java , привел разделы в соответствии с описаниями из README. Пожалуйста, обрати особое внимание на раздел сторис и инициализацию. Вроде как readme всё делалось, но вдруг что не так.

2024-07-03 14:48 UTC, xeewii requested changes

2024-07-03 14:48 UTC, xeewii commented on source/includes/_init.md.erb
> +		REES46.setOnMessageListener(new MessagingService.OnMessageListener() {
REES46 вроде надо заменить на 	<%= config[:android_sdk_package_name] %>
Выше тоже

2024-07-03 14:48 UTC, xeewii commented on source/includes/_stories.md.erb
> +```java
Здесь, кстати, стоит поправить основное описание, т.е. убрать "Request path `/story/STORY_ID`" и заменить STORY_ID н story_code

2024-07-03 14:57 UTC, xeewii submitted a review, later dismissed

2024-07-03 15:21 UTC, Nelfimov submitted a review, later dismissed
конфликты. После резолва - запрашивай ревью у Андрея

2024-07-03 17:40 UTC, xeewii approved these changes

2024-07-03 19:46 UTC, TorinAsakura approved these changes

2024-07-03 19:46 UTC, merged