docs(stories): stories on request description js
rees46/api-docs pull request #60
Opened 2024-07-01 15:34 UTC by gochicus

к этой задаче:
- https://github.com/rees46/planning/issues/825

2024-07-01 17:32 UTC, aliceinapple approved these changes

2024-07-02 06:09 UTC, Nelfimov requested changes

2024-07-02 06:09 UTC, Nelfimov commented on source/includes/_stories.md.erb
> +sdk.startStory() {
@aliceinapple это же внутренний метод `Stories`. Клиент будет пользоваться `r46('start_stories', нет?

2024-07-02 07:03 UTC, aliceinapple commented on source/includes/_stories.md.erb
> +sdk.startStory() {
> @aliceinapple это же внутренний метод `Stories`. Клиент будет пользоваться `r46('start_stories', нет?

Верно

@gochicus 

Для запуска сториз (кампании) клиент будет вызывать `r46('start_stories', 'код блока сториз')`

2024-07-02 07:43 UTC, aliceinapple commented
@gochicus 

Кажется еще не хватает создания экземпляра класса сториз

Получается так:
- клиент будет вызывать `r46('start_stories', 'код блока сториз')`
- затем происходит создание блока сториз и экземпляра класса `Stories`, установка `startCampain` в `true`

```js
case 'start_stories':
        if (command[1] && typeof command[1] === 'string') {
          const code = command[1]

          const container = createStoryBlock(this.label.fullName(), code)

          const stories = new Stories(this, container);
          stories.startCampaign = true
        }
        break;
```
- Создание блока описано верно
- А затем вызов `startStory` внутри класса `Stories` и запуск кампании если `stories.startCampaign = true`

Не знаю как точно это должно быть описано в документации, @Nelfimov поправь, если это лишнее

2024-07-02 07:46 UTC, Nelfimov commented
@aliceinapple докуменацию пишем для клиентов. Поэтому смотри на это глазами пользователя а не разраба.

Тебе нужно показать как пользоваться публичными методами.

2024-07-02 08:00 UTC, gochicus commented
@aliceinapple ок, создание убираем. Тогда как, оставляем только инициализацию? Что-то ещё пользователь должен знать?

2024-07-02 08:10 UTC, aliceinapple commented
> @aliceinapple ок, создание убираем. Тогда как, оставляем только инициализацию? Что-то ещё пользователь должен знать?

@gochicus 
По сути ему нужно знать только то, что он может запустить кампанию вызвав эту функцию `r46('start_stories', 'код блока сториз')` с нужными аргументами, либо после инициализации, либо по какому-то действию и все.

2024-07-02 10:17 UTC, aliceinapple approved these changes

2024-07-02 10:19 UTC, Nelfimov commented
@aliceinapple почему одобрила? Вроде же договорились что в документации показываем доступные методы. Ты даже выше сама описала что тут должно быть: https://github.com/rees46/api-docs/pull/60#issuecomment-2202266267

2024-07-02 11:21 UTC, gochicus commented
@Nelfimov тогда как? инициация осталась, создание блока сторис я убрал, а если код: 

```case 'start_stories':
        if (command[1] && typeof command[1] === 'string') {
          const code = command[1]

          const container = createStoryBlock(this.label.fullName(), code)

          const stories = new Stories(this, container);
          stories.startCampaign = true
        }
        break;
```
внутри экземпляра класса сторис, то как это полезно пользователю?

2024-07-02 11:23 UTC, Nelfimov commented
@gochicus `.startStories` - это внутренний метод. Пользователь СДК его не увидит.

![image](https://github.com/rees46/api-docs/assets/44067768/a4efbc99-6e0d-499f-a4b0-e42136842392)

Вика дала корректный код https://github.com/rees46/api-docs/pull/60#issuecomment-2202266267

2024-07-02 11:40 UTC, gochicus commented
@Nelfimov посмотри, пожалуйста, в таком формате нормальное описание?

2024-07-02 11:48 UTC, Nelfimov requested changes

2024-07-02 11:48 UTC, Nelfimov commented on source/includes/_stories.md.erb
> +// The 'start_stories' command is used to create a block of stories and start a campaign.
`The 'start_stories' command is used to start story campaign programmatically (e.g. on button click)`

2024-07-02 11:48 UTC, Nelfimov commented on source/includes/_stories.md.erb
> +// The second argument, 'command', must be a string.
`The second argument is the ID of the story campaign.`

2024-07-02 11:48 UTC, Nelfimov commented on source/includes/_stories.md.erb
> +// A stories block is created using the createStoryBlock function.
27-29 - внутренняя кухня СДК

2024-07-02 12:34 UTC, gochicus commented
@Nelfimov поменял немного в связи с планируемым отходом от кампаний

2024-07-02 12:35 UTC, Nelfimov approved these changes

2024-07-02 12:40 UTC, aliceinapple approved these changes

2024-07-02 15:56 UTC, TorinAsakura approved these changes

2024-07-02 16:01 UTC, merged