docs(products):  respones deails description
rees46/api-docs pull request #72
Opened 2024-07-05 12:15 UTC by gochicus

https://github.com/rees46/planning/issues/958

2024-07-05 12:21 UTC, gochicus commented
Дополнил описание полей ответа на основании этого запроса из задачи:
https://api.rees46.ru/products?shop_id=357382bf66ac0ce2f1722677c59511
@davidgegiya подскажи, пожалуйста, где можно посмотреть возвращаемые ответы ? Метод: `GET https://<%= config[:api_endpoint] %>/products` вроде твой. Уже имеющееся описание содержит элементы в массиве product, которых нет в ответе на запрос (который приложил к сообщению), но есть и поля ответа, которые не описаны.

2024-07-05 13:49 UTC, davidgegiya commented
@gochicus Сложный вопрос. Результаты формируются в `packages/recommender-service/src/Core/SearchTrait.php:771`, ниже в том же методе, они дополняются агрегациями. Идёт вызов метода `packages/recommender-service/src/Core/SearchTrait.php:689`, там дополняется структура, которая формируется посредством вызова `structureForTemplate` - `packages/core/src/Model/Item.php:120`

2024-09-06 09:44 UTC, gochicus commented
<details><summary>Пруф. С разметкой всё ок</summary>

<img width="1920" alt="request-product-response  png" src="https://github.com/user-attachments/assets/b442fbc8-21f1-4494-b7a4-0b0e832e0a09">

</details>

2024-09-06 11:53 UTC, davidgegiya requested changes

2024-09-06 11:53 UTC, davidgegiya commented on source/includes/_products.md.erb
> +|                |                  | * picture – brand picture (string)
ещё `count` - количество совпадений

2024-09-06 11:53 UTC, davidgegiya commented on source/includes/_products.md.erb
> +|                |                  | * url - category URL (string)
ещё `parent` и `alias` https://github.com/rees46/web/blob/917a57dd697f3cd022130eb1bd4d9daa77f7f521/packages/recommender-service/src/Core/SearchTrait.php#L878

2024-09-06 11:53 UTC, davidgegiya commented on source/includes/_products.md.erb
> +|                |                  | * values – array of values (object). Has the following properties:
ещё `priority` и `ranges` https://github.com/rees46/web/blob/917a57dd697f3cd022130eb1bd4d9daa77f7f521/packages/recommender-service/src/Core/SearchTrait.php#L826

2024-09-06 11:53 UTC, davidgegiya commented on source/includes/_products.md.erb
> +|                |                  | Additional properties. If a parameter "extended" is passed in the request
`extended` используется только в рекомендере, в листинге он не используется

2024-09-09 10:49 UTC, davidgegiya approved these changes

2024-09-09 20:32 UTC, TorinAsakura approved these changes

2024-09-09 20:32 UTC, merged