docs(includes): kotlin documentation updated
rees46/api-docs pull request #75
Opened 2024-07-12 12:11 UTC by gochicus

https://github.com/rees46/planning/issues/1225

2024-07-12 12:48 UTC, xeewii requested changes

2024-07-12 12:48 UTC, xeewii commented on source/includes/_recommendations.md.erb
> +
На эту строчку добавить `})`

2024-07-12 12:48 UTC, xeewii commented on source/includes/_recommendations.md.erb
> + })
Форматирование слетело

2024-07-12 12:48 UTC, xeewii commented on source/includes/_search.md.erb
> +       params.put(SearchParams.Parameter.NO_CLARIFICATION, true)
Добывать в конце строки `//Disable clarification search`
Ниже такую же строчку удалить

2024-07-12 12:48 UTC, xeewii commented on source/includes/_search.md.erb
> +         })
Форматирование слетело

2024-07-12 12:48 UTC, xeewii commented on source/includes/_search.md.erb
> +    Log.i(TAG, "Search blank response: $searchBlankResponse")
Ты тут для джавы вроде поменял, а нужно только для котлина)

2024-07-14 22:17 UTC, xeewii requested changes

2024-07-14 22:17 UTC, xeewii commented on source/includes/_search.md.erb
>  ```
Добавить 
`sdk.searchManager.searchFull("SEARCH_QUERY", params, { searchFullResponse ->
    Log.i(TAG, "Search full response: $searchFullResponse")
})`

2024-07-15 07:22 UTC, xeewii requested changes

2024-07-15 07:22 UTC, xeewii commented on source/includes/_search.md.erb
> +params.put(SearchParams.Parameter.FASHION_SIZES, filters)
Добавить
`sdk.searchManager.searchFull("SEARCH_QUERY", params, { searchFullResponse -> 
Log.i(TAG, "Search full response: $searchFullResponse") 
})`

2024-07-15 07:24 UTC, xeewii requested changes

2024-07-15 07:24 UTC, xeewii commented on source/includes/_search.md.erb
> +sdk.searchManager.searchFull("SEARCH_QUERY", params, { searchFullResponse -> Log.i(TAG, "Search full response: $searchFullResponse") })
Эту строчку вниз самый надо)
Плюс отформатируй её так же, как другие подобные

2024-07-15 07:34 UTC, xeewii submitted a review, later dismissed

2024-07-15 12:26 UTC, TorinAsakura approved these changes

2024-07-15 12:26 UTC, merged