docs(notification_service): draft
rees46/api-docs pull request #9
Opened 2024-05-15 16:27 UTC by gochicus

2024-05-15 16:37 UTC, TorinAsakura commented
что за draft?

2024-05-15 16:37 UTC, TorinAsakura commented
@yart просил уже миллион раз - отруби чёртовы экшены

2024-05-31 01:18 UTC, maksmart96 requested changes

2024-05-31 01:18 UTC, maksmart96 commented on source/includes/_notification_service.md.erb
> +let notificationService = NotificationService(sdkInstance: personalizationSDK)
`NotificationService(sdk: personalizationSDK)` - не `sdkInstance`

2024-05-31 01:18 UTC, maksmart96 commented on source/includes/_notification_service.md.erb
> +    UIApplication.shared.registerForRemoteNotifications()
`NotificationService` самостоятельно запросит регистрацию
`UIApplication.shared.registerForRemoteNotifications()` не нужно вызывать самостоятельно

2024-05-31 01:18 UTC, maksmart96 commented on source/includes/_notification_service.md.erb
> +    // Initialize NotificationService
```
// Initialize iOS SDK first 
var personalizationSDK = createPersonalizationSDK(shopId: "SHOP_ID", autoSendPushToken: true)

// Initialize NotificationService with pre-created instance of iOS SDK
let notificationService = NotificationService(sdk: personalizationSDK)
```

2024-05-31 01:18 UTC, maksmart96 commented on source/includes/_notification_service.md.erb
> +        notificationService.didRegisterForRemoteNotifications(with: deviceToken)
`notificationService?.didRegisterForRemoteNotificationsWithDeviceToken(deviceToken: deviceToken)`

2024-05-31 01:52 UTC, closed without merging