docs(includes): transact method response change, message notification
rees46/api-docs pull request #94
Opened 2024-08-19 14:40 UTC by gochicus

https://github.com/rees46/planning/issues/844

2024-08-21 11:36 UTC, gochicus commented
@davidgegiya посмотри, пожалуйста, когда время будет

2024-08-21 11:59 UTC, davidgegiya requested changes

2024-08-21 11:59 UTC, davidgegiya commented on source/includes/_transactionals.md.erb
> +| 200              | { "200" }                                                | The request was successful.                                                                  |
В ответе структура кода.
```
{"code": "12345"}
```

2024-08-22 06:47 UTC, davidgegiya approved these changes

2024-08-22 10:22 UTC, TorinAsakura approved these changes

2024-08-22 10:23 UTC, merged