docs(mobile_push_notifications): custom push android description
rees46/api-docs pull request #99
Opened 2024-08-23 09:20 UTC by gochicus

https://github.com/rees46/planning/issues/1493

2024-08-23 09:21 UTC, DanielGreenEngineer submitted a review, later dismissed

2024-08-23 10:21 UTC, davidgegiya requested changes

2024-08-23 10:21 UTC, davidgegiya commented on source/includes/_mobile_push_notifications.md.erb
> +`'notification' => [
Это не так работает. Проверь самый последний PR, актуальный код там. Значение берётся из настройки кампании, отдельное поле, которое Миша запилил на фронте. Создатель цепочки сам задаёт значение названия коллбека и далее отслеживает его по названию

2024-08-29 15:12 UTC, DanielGreenEngineer approved these changes

2024-08-29 16:16 UTC, davidgegiya approved these changes

2024-08-30 07:29 UTC, TorinAsakura approved these changes

2024-08-30 07:29 UTC, merged